	<h5>Título de nível 5</h5>
				
				<p>
					<strong>Parágrafo:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut elit ipsum. Nunc laoreet, purus sit amet euismod tincidunt, eros urna gravida lorem, vel vehicula arcu enim in erat. Aliquam erat volutpat. Quisque bibendum enim a mauris tincidunt accumsan. Proin eget mauris mi, ac vestibulum nisl. Aliquam erat volutpat. Donec non dapibus turpis. Morbi non arcu dolor, at tempus libero. <a href="#">Ut sed tortor at tortor mattis sodales.</a> Aliquam tempus nulla vitae massa suscipit ullamcorper. Morbi eu massa turpis, eget varius ante. Nulla interdum sagittis egestas. Ut nec bibendum orci. Cras ac nisi nec metus mollis tempor. Proin id varius mauris. Phasellus id urna in ipsum laoreet placerat. Nulla sagittis orci vel eros laoreet at hendrerit orci blandit.
				</p>
				
				<strong>Lista</strong>

				<ul>
					<li>Software</li>
					<li>Linux</li>
					<li>PHP</li>
				</ul>
				
				<strong>Lista Ordenada</strong>
				<ol>

					<li>Software</li>
					<li>Linux</li>
					<li>PHP</li>
				</ol>
				
				
				<form name="form1">
					<fieldset>
					
						<legend>Formulário de contato</legend>

						
						<p>
							Nome:<br /><input type="text" name="nome" />
						</p>
						
						<p>
							Email:<br /><input type="text" name="email" />
						</p>
						
						<p>
							Assunto:<br />

							<select name="assunto">
								<option value="">Sugestão</option>
								<option value="">Críticas</option>
								<option value="">Elogios</option>
							</select>
						</p>
						
						<p>

							<input type="radio" name="radio">Masculino <input type="radio" name="radio">Feminino
						</p>
						
						<p>
							<input type="checkbox" name="checkbox">Receber informações por e-mail?
						</p>
						
						<p>
							Digite uma mensagem:<br /><textarea name="textearea" rows="4"></textarea>
						</p>

						
						<p>
							<input type="submit" value="ENVIAR MENSAGEM" />
						</p>
									
					</fieldset>
				</form>
				
				
				<div class="w50">
					<strong>Div com 50% de largura<BR />Aplicação: class="w50"</strong>
					<p>

					Parágrafo: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut elit ipsum. Nunc laoreet, purus sit amet euismod tincidunt, eros urna gravida lorem, vel vehicula arcu enim in erat. Aliquam erat volutpat. Quisque bibendum enim a mauris tincidunt accumsan. Proin eget mauris mi, ac vestibulum nisl. Aliquam erat volutpat. Donec non dapibus turpis. Morbi non arcu dolor, at tempus libero. Ut sed tortor at tortor mattis sodales. Aliquam tempus nulla vitae massa suscipit ullamcorper. Morbi eu massa turpis, eget varius ante. Nulla interdum sagittis egestas. Ut nec bibendum orci. Cras ac nisi nec metus mollis tempor. Proin id varius mauris. Phasellus id urna in ipsum laoreet placerat. Nulla sagittis orci vel eros laoreet at hendrerit orci blandit.
					</p>
				</div>
				<div class="w50">
					<strong>Div com 50% de largura<BR />Aplicação: class="w50"</strong>
					<p>
					Parágrafo: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut elit ipsum. Nunc laoreet, purus sit amet euismod tincidunt, eros urna gravida lorem, vel vehicula arcu enim in erat. Aliquam erat volutpat. Quisque bibendum enim a mauris tincidunt accumsan. Proin eget mauris mi, ac vestibulum nisl. Aliquam erat volutpat. Donec non dapibus turpis. Morbi non arcu dolor, at tempus libero. Ut sed tortor at tortor mattis sodales. Aliquam tempus nulla vitae massa suscipit ullamcorper. Morbi eu massa turpis, eget varius ante. Nulla interdum sagittis egestas. Ut nec bibendum orci. Cras ac nisi nec metus mollis tempor. Proin id varius mauris. Phasellus id urna in ipsum laoreet placerat. Nulla sagittis orci vel eros laoreet at hendrerit orci blandit.
					</p>
				</div>				
				
				<div class="w30">

					<strong>Div com 30% de largura<BR />Aplicação: class="w30"</strong>
					<p>
					Parágrafo: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut elit ipsum. Nunc laoreet, purus sit amet euismod tincidunt, eros urna gravida lorem, vel vehicula arcu enim in erat. Aliquam erat volutpat. Quisque bibendum enim a mauris tincidunt accumsan. Proin eget mauris mi, ac vestibulum nisl. Aliquam erat volutpat. Donec non dapibus turpis. Morbi non arcu dolor, at tempus libero. Ut sed tortor at tortor mattis sodales. Aliquam tempus nulla vitae massa suscipit ullamcorper. Morbi eu massa turpis, eget varius ante. Nulla interdum sagittis egestas. Ut nec bibendum orci. Cras ac nisi nec metus mollis tempor. Proin id varius mauris. Phasellus id urna in ipsum laoreet placerat. Nulla sagittis orci vel eros laoreet at hendrerit orci blandit.
					</p>
				</div>
				<div class="w30">
					<strong>Div com 30% de largura<BR />Aplicação: class="w30"</strong>

					<p>
					Parágrafo: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut elit ipsum. Nunc laoreet, purus sit amet euismod tincidunt, eros urna gravida lorem, vel vehicula arcu enim in erat. Aliquam erat volutpat. Quisque bibendum enim a mauris tincidunt accumsan. Proin eget mauris mi, ac vestibulum nisl. Aliquam erat volutpat. Donec non dapibus turpis. Morbi non arcu dolor, at tempus libero. Ut sed tortor at tortor mattis sodales. Aliquam tempus nulla vitae massa suscipit ullamcorper. Morbi eu massa turpis, eget varius ante. Nulla interdum sagittis egestas. Ut nec bibendum orci. Cras ac nisi nec metus mollis tempor. Proin id varius mauris. Phasellus id urna in ipsum laoreet placerat. Nulla sagittis orci vel eros laoreet at hendrerit orci blandit.
					</p>
				</div>			
				<div class="w30">
					<strong>Div com 30% de largura<BR />Aplicação: class="w30"</strong>
					<p>
					Parágrafo: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut elit ipsum. Nunc laoreet, purus sit amet euismod tincidunt, eros urna gravida lorem, vel vehicula arcu enim in erat. Aliquam erat volutpat. Quisque bibendum enim a mauris tincidunt accumsan. Proin eget mauris mi, ac vestibulum nisl. Aliquam erat volutpat. Donec non dapibus turpis. Morbi non arcu dolor, at tempus libero. Ut sed tortor at tortor mattis sodales. Aliquam tempus nulla vitae massa suscipit ullamcorper. Morbi eu massa turpis, eget varius ante. Nulla interdum sagittis egestas. Ut nec bibendum orci. Cras ac nisi nec metus mollis tempor. Proin id varius mauris. Phasellus id urna in ipsum laoreet placerat. Nulla sagittis orci vel eros laoreet at hendrerit orci blandit.
					</p>

				</div>	
				
				<hr />
